name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get release info
        run: |
          echo "tag-name=$(cat package.json | jq .version)" >> $GITHUB_OUTPUT
          echo "release-name=$(cat package.json | jq .version)" >> $GITHUB_OUTPUT
        id: release-info
      - name: Check the build
        run: |
          npm ci
          npm run build
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release-info.outputs.tag-name }}
          release_name: v${{ steps.release-info.outputs.release-name }}
        id: create-release

