name: Release

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - name: Make assets file
        run: |
          zip -r yajsw.zip yajsw/*
      - name: Get release info
        run: |
          echo "tag-name=v$(cat package.json | jq '.version|split(".")[0]')" >> $GITHUB_OUTPUT
          echo "release-name=v$(cat package.json | jq '.version|split(".")[0]')" >> $GITHUB_OUTPUT
        id: release-info
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release-info.outputs.tag-name }}
          release_name: ${{ steps.release-info.outputs.release-name }}
        id: create-release
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: yajsw.zip
          asset_name: yajsw.zip
          asset_content_type: application/zip
